### PR TITLE
Add mail.imap.peek

### LINKED ISSUE #5: Unseen messages become seen
Using IMAP, UNSEEN messages become SEEN.

A possible fix could be to implement [mail.imap.peek](https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html#mail.imap.peek), according to documentation:

> If set to true, use the IMAP PEEK option when fetching body parts, to avoid setting the SEEN flag on messages.

### PR DESCRIPTION
**Pull request by kiaruzza**
Fix https://github.com/oblac/jodd-mail/issues/5

### CODE REVIEW

**Comment by kiaruzza** [comment]
@igr how can I resolve this?

**Comment by igr** [comment]
Hey @kiaruzza what do you need to resolve? It looks fine, I will merge today :)

**Comment by kiaruzza** [comment]
> Hey @kiaruzza what do you need to resolve? It looks fine, I will merge today :)

Sorry, I was referring to project's code coverage. If it's ok, better this way. Tnx :)

**Comment by igr** [comment]
Yeah, just ignore it, the delta is really low: (0.05) :)))

**Review by igr — APPROVED** [review]

**Pull request merged**
