### PR TITLE
Implemented equals() and hashCode() on EmailAddress

### PR DESCRIPTION
**Pull request by MibbitTom**
Change made so we can see if a List contains() an EmailAddress.

Please let me know if any amendments are required.

### CODE REVIEW

**Review by igr — APPROVED** [review]
LGTM :)

**Comment by igr** [comment]
Thank you !

**Comment by MibbitTom** [comment]
Nice one! Look forward to it hitting maven :)

**Comment by igr** [comment]
very soon! :)

**Comment by igr** [comment]
Just released v7.0.1 @MibbitTom !

**Pull request merged**
